[tool.poetry]
name = "project2-sozinova-uliana-m25-555"
version = "0.1.0"
description = "A simple console-based database management system in Python with CRUD operations, caching, error handling, and formatted output."
authors = ["Uliana Sozinova <uliana.so-dev@yandex.ru>"]
readme = "README.md"
packages = [
    { include = "src" },
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
prompt = "^0.4.1"
prettytable = "^3.16.0"
asciinema = "^2.4.0"

[tool.poetry.scripts]
database = "src.primitive_db.main:main" 

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
[dependency-groups]
dev = [
    "ruff (>=0.14.3,<0.15.0)"
]